#apiVersion: v1
#kind: Service
#metadata:
#  name: argocd-server-nodeport
#  namespace: argocd
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 8080
#      nodePort: 30007 # Specify the nodePort you want to use, or let Kubernetes allocate one for you.
#  selector:
#    app.kubernetes.io/name: argocd-server

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: combined-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/plum7ree/distributed-priority-queue/tree/main
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
