apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007 # Specify the nodePort you want to use, or let Kubernetes allocate one for you.
  selector:
    app.kubernetes.io/name: argocd-server